main:
# incoming pub sub message
  params: [event]
  steps:
  # init vars 
    - initvars:
       assign:
         - sendmail: {}
         - shiplabel: {}
         - message: {}
         - cloudrun: {}
    - decode_pubsub_message:
    # decode and output at end of wf
        assign:
           - base64: ${base64.decode(event.data.message.data)}
           - message: ${text.decode(base64)}
    - parallelwf:
    # parallel workflow - 2 functions
       parallel:
         #shared variables: [userProfile, recentItems]  # userProfile and recentItems are shared 
         shared: [sendmail, shiplabel]
         branches:
           - b_SendMail:
               steps:
                 - call_sm:
                     call: http.get
                     args:
                       # specify cloud function trigger
                       url: https://europe-west1-qwiklabs-gcp-02-68856f1b0db7.cloudfunctions.net/send_mail
                     result: sm
                 - result-sm:
                     assign:
                       - sendmail: ${sm.body}
           - b_ShipLabel:
               steps:
                 - call_sl:
                     call: http.get
                     args:
                        # specify cloud function trigger
                        url: https://europe-west1-qwiklabs-gcp-02-68856f1b0db7.cloudfunctions.net/ship_label 
                     result: sl
                 - result-sl:
                     assign:
                       - shiplabel: ${sl.body}

    - call-cloudrun:
        call: http.post
        args:
          url: https://cr-u23uybcw6q-uc.a.run.app
          auth:
            type: OIDC
          body:
            input: ${shiplabel}
        result: cr_result
    - result-cr:
        assign:
          - cloudrun: ${cr_result.code}
    - result:
        # output results
        return: 
          - ${message}
          - ${shiplabel}
          - ${sendmail}
          # ${cloudrun}
          - "Cloud Run service updated"
          - "End of Workflow"
